name: flux_firebase
description: A Firebase package for FluxStore apps
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fstore:
    path: ../../
  inspireui: 2.1.0

  # FIREBASE PACKAGES
  firebase_core: 2.31.1
  firebase_analytics: 10.10.6
  firebase_auth: 4.19.6
  firebase_remote_config: 4.4.6
  firebase_dynamic_links: 5.5.6
  cloud_firestore: 4.17.4
  firebase_remote_config_web: 1.6.6

  # Additional Firebase packages. To prevent unexpected upgrade.
  firebase_core_platform_interface: 5.0.0
  firebase_analytics_platform_interface: 3.10.7
  firebase_auth_platform_interface: 7.2.7
  firebase_remote_config_platform_interface: 1.4.34
  firebase_dynamic_links_platform_interface: 0.2.6+34
  cloud_firestore_platform_interface: 6.2.4
  firebase_messaging_platform_interface: 4.5.36


  # PUSH NOTIFICATION
  firebase_messaging: 14.9.3

  # OTHERS
  intl: any
  timeago: 3.6.1
  flutter_local_notifications: ^14.0.0+2
  share: 2.0.4
  provider: 6.1.2
  collection: any
  easy_debounce: 2.0.3

flutter:
  uses-material-design: true

